"""add repository workspace and file hidden flag

Revision ID: e86c92b99f15
Revises: 720c10308d09
Create Date: 2026-07-13 00:09:10.162939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e86c92b99f15'
down_revision: Union[str, Sequence[str], None] = '720c10308d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_workspace',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('supported_files', sa.Integer(), nullable=False),
    sa.Column('ignored_files', sa.Integer(), nullable=False),
    sa.Column('folder_count', sa.Integer(), nullable=False),
    sa.Column('repository_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('language_distribution', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'scanning', 'ready', 'failed')", name=op.f('ck_repository_workspace_status')),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_repository_workspace_repository_id_repositories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repository_workspace')),
    sa.UniqueConstraint('repository_id', name=op.f('uq_repository_workspace_repository_id'))
    )
    op.add_column('files', sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_hidden')
    op.drop_table('repository_workspace')
    # ### end Alembic commands ###
